[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "twosteps_logger"
version = "1.0.1"
description = "Custom structured logger library for Elasticsearch with monthly indices"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Twosteps"}
]
keywords = ["logging", "elasticsearch", "twosteps_logger", "twosteps"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "elasticsearch>=8.0.0,<9.0.0",
    "opentelemetry-sdk>=1.24.0",
    "opentelemetry-exporter-otlp-proto-grpc>=1.24.0",
    "opentelemetry-exporter-otlp-proto-http>=1.24.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
]
demo = [
    "fastapi>=0.110.0",
    "uvicorn>=0.30.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["twosteps_logger*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=twosteps_logger --cov-report=term-missing --cov-fail-under=80"

